### ISSUE TITLE
Documentation: $MAMBA_USER not supported by buildah (?)

### ISSUE THREAD

**Issue by nthiery** [mamba-org/micromamba-docker#119]
The documentation of the mambaorg/micromamba recommends the use of $MAMBA_USER
to avoid hardcoding the mamba user (which is nice).

However, this seems not to work when using buildah rather than Docker: see e.g. this build failure:

https://gitlab.dsi.universite-paris-saclay.fr/L1InfoInitiationScienceDonnees/ComputerLab/-/jobs/6723#L36

For now, I am working around it by hardcoding mambauser which does the job for now.
So nothing urgent :-)

Context: buildah is a convenient tool to build docker images in CI jobs as it does not require
special privileges, like e.g. docker-in-docker does.

**Comment by wholtz** [comment]
Hi Nicholas -- thank you for your report and interest in micromamba.

We could try to work around the limitations of buildah, but it would be
better if this was addressed within buildah. Have you submitted an issue
with the buildah project? If so, please link to that issue here.

**Comment by maresb** [comment]
Does it work if you do the chown inside the RUN command?

> as it does not require special privileges

I don't know anything about buildah, but I wonder if it is failing due to lack of privileges or similar? It looks to me like `MAMBA_USER` is correctly set.

**Comment by maresb** [comment]
Or maybe buildah simply fails to perform the variable substitution in this case?

**Comment by maresb** [comment]
Hi @nthiery, I took a closer look, and it looks like buildah has had some related issues https://github.com/containers/buildah/issues/2192. It seems that these issues may be fixed in the latest versions, but from your build logs I couldn't figure out which version of `tomkukral/buildah` you are using. I tried to pull the container based on the SHA256 indicated in the logs, and I received `500 Internal Server Error` which makes me suspect that the image has expired. So I wonder if your runner is caching an old version of buildah. If so, then upgrading might resolve the issue. (Just change `tomkukral/buildah`→`tomkukral/buildah:0.30`.)

Also, I would strongly recommend pinning a specific image instead of using `mambaorg/micromamba:latest`, because we are still frequently making breaking changes. We don't have any tags which are stable; `0.20.0` will change if we change the `micromamba-docker` Dockerfile, and `git-f77a64b` will change if the upstream version changes. Thus our recommendation is to use `mambaorg/micromamba:git-f77a64b@sha256:b2128df1ddbcfc6853a6c50a66b02548cec55c3df862854ffd9b652d251358c4` to pin the version. (@wholtz, perhaps we should implement the obvious solution of simply generating combined tags.)

**Comment by nthiery** [comment]
Ah ah, $MAMBA_USER indeed works with the latest buildah image. Thanks
@maresb for the tip and sorry for the noise!

Thanks too for the tip for mambaorg; that being said, if it can be helpful for you to
have beta testers that use the latest version in a variety of context, I don't mind taking
the risk.

**Comment by maresb** [comment]
No worries @nthiery, glad to have helped you out. Also I'm glad my new `$MAMBA_USER` feature is working.

It is indeed helpful to have testers on latest. Thanks for being brave.

I'm not an official maintainer here, so you'll have to close out this issue for me.
