### ISSUE TITLE
filesystem error when running in CI

### ISSUE THREAD

**Issue by alonisser** [mamba-org/micromamba-docker#214]
I'm getting critical libmamba filesystem error: cannot make absolute path: Invalid argument []
(With either this docker, or straight micromamba installation) 
When trying to run in gitlab CI runner 
```bash
create -f conda.yaml -y

```
Adding -p and a specific sub path didn't help, nor changing MAMBA_ROOT_PREFIX to be in the project folder

the full stack trace

```
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/root/.mambarc'
trace    libmamba Configuration not found at '/root/.condarc'
trace    libmamba Configuration not found at '/root/.conda/condarc.d'
trace    libmamba Configuration not found at '/root/.conda/condarc'
trace    libmamba Configuration not found at '/root/.conda/.condarc'
trace    libmamba Configuration not found at '/builds/ourcompany/data-science/surveys-clustering/survey-answers-clustering/mamba/.mambarc'
trace    libmamba Configuration not found at '/builds/ourcompany/data-science/surveys-clustering/survey-answers-clustering/mamba/condarc.d'
trace    libmamba Configuration not found at '/builds/ourcompany/data-science/surveys-clustering/survey-answers-clustering/mamba/condarc'
trace    libmamba Configuration not found at '/builds/ourcompany/data-science/surveys-clustering/survey-answers-clustering/mamba/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'file_specs'
critical libmamba filesystem error: cannot make absolute path: Invalid argument []
info     libmamba ****************** Backtrace End ********************
```
I'd appreciate helps or pointers

(Locally it does run as expected of course)

**Comment by wholtz** [comment]
Hello @alonisser - thanks for the report. Because you are getting the same error with the `mambaorg/micromamba` docker image and with directly installing the `micromamba` program, this is not an issue with the docker image, but an issue with the `micromamba` program. Therefore, I am going to transfer this issue to the [mamba/libmamba/micromamba repo](https://github.com/mamba-org/mamba).

 It will be difficult to help diagnose your problem if we are not able to reproduce the error. Can you please post a minimal `conda.yaml` that has this behavior and tell us more about the GitLab CI configuration you are using, including your `.gitlab-ci.yaml`. Is this happening with a runner on [Gitlab.com](https://www.gitlab.com/) or with self-hosted runner? If you could create a minimal, public repo on [Gitlab.com](https://www.gitlab.com/) that demonstrates the problem, that would be great.

With the information I have so far, my only guess is that your Gitlab running is out of disk space.

**Comment by wholtz** [comment]
GitHub isn't letting me transfer this existing issue to [https://www.github.com/mamba-org/mamba]. Can you please re-post your issue there? Thanks!

**Comment by alonisser** [comment]
Thanks will do

**Comment by wholtz** [comment]
Moved to https://github.com/mamba-org/mamba/issues/1975
