### ISSUE TITLE
Problem with M1 Mac - silently looking for arm packages

### ISSUE THREAD

**Issue by danudwary** [mamba-org/micromamba-docker#253]
I'm going to leave a breadcrumb here in case anyone else encounters this. I was having trouble building a micromamba container using the supplied instructions. I seemed to be completely unable to pull dependencies from the "bioconda" channel, with a message saying that the dependencies could not be found: 
`error    libmamba Could not solve for environment specs`

After switching to a miniconda3 contianer, I encountered a completely different lib error, and eventually found an explanation [here](https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc). 

It turns out that by building with docker on my M1 Mac, micromamba was searching for arm packages in the bioconda channel, which do not exist. This is easily fixed by adding "`--platform=linux/amd64`" to the FROM line in the Dockerfile. I don't believe this is a micromamba issue, per se, but rather M1 Mac docker weirdness, but it was confusing one, for me, and maybe this advice helps someone else out down the road. Perhaps something in the error output specifying which processor build types were being searched for would have clued me in faster.

**Comment by wholtz** [comment]
Thanks for the feedback Dan. I'll work on adding a note to the documentation. 

As for the error messages, that would need to be done in the upstream [mamba project](https://github.com/mamba-org/mamba). There have been [similar issues](https://github.com/mamba-org/mamba/issues/2120) reported there.

**Comment by maresb** [comment]
I don't think that this is the right repository to document this stuff, but I don't know what is, and I have had various similar headaches trying to get things working for people on M1 and M2. I don't use Mac or bioconda myself, but a few (not entirely thorough) experiments indicate a pretty bad performance hit when using amd64 emulation on M1/M2, as opposed to running native arm64.

In contrast with bioconda, conda-forge offers M1/M2 support for certain packages (package maintainers must opt-in). The correct platform depends on whether one is outside of or inside of Docker, since the operating system is respectively OSX or Linux. The platform names are `osx-arm64` and   `linux-aarch64`, where aarch64 is synonymous with arm64.

**Comment by danudwary** [comment]
FWIW, my use case is to build Docker containers on my laptop, upload to dockerhub, and then pull down to run on an HPC environment that doesn't permit building on cluster. So, I'm personally not even a little bit concerned about arm efficiency. And I primarily need to access bioinformatics packages on bioconda, which aren't present in conda-forge. But thanks! I'm sure others can use this good advice!

**Comment by wholtz** [comment]
I have added a [FAQ that addresses this issue](https://github.com/mamba-org/micromamba-docker/blob/main/FAQ.md#why-am-i-getting-the-error-libmamba-could-not-solve-for-environment-specs).
