### ISSUE TITLE
Build Request for `mambaorg/micromamba:jammy`

### ISSUE THREAD

**Issue by ChaonengQuan** [mamba-org/micromamba-docker#573]
Hi Micromamba team,

## Summary

Can I request a latest build and release on `mambaorg/micromamba:jammy` image so that it will use the latest version of `mircomamba`?

The `jammy` mircomamba image is using `1.5.10` and last release was on `Sep 23, 2024 at 9:13 am` (3 month ago from Dec 26th)

## Motivation
`1.5.11` contains the fix for our software use case

Thanks,
Chaoneng

**Comment by wholtz** [comment]
Hello @ChaonengQuan . With the move to micromamba 2.x, we changed our tags to use number instead of version names. Please see if `mambaorg/micromamba:ubuntu22.04` works for you.

1.5.10 was the last 1.x version of micromamba we released docker images for. We are not planning on releasing any more 1.x docker images.

**Comment by ChaonengQuan** [comment]
Thanks for the quick response!

I checked `mambaorg/micromamba:ubuntu22.04`, and it appears to contain micromamba version `2.0.5`. Since this is a major version upgrade from `1.5.10`, some internal investigation is needed before making the change.
