### ISSUE TITLE
Don't mess with PATH

### ISSUE THREAD

**Issue by maresb** [mamba-org/micromamba-docker#61]
I'd prefer to get rid of [this line](https://github.com/mamba-org/micromamba-docker/blob/92e4c6700d155f9b8bdfb3566866a5f1dfba3e29/Dockerfile#L25) which prepends `$MAMBA_ROOT_PREFIX/bin` to `PATH`.

Here are a few reasons why I think that line is a bad idea:
- Suppose `MAMBA_ROOT_PREFIX` is changed by the user. Then the default is still on the path, but the new value is not.
- It's Mamba's job to modify the environment. (Mamba can always be triggered by `SHELL` or `ENTRYPOINT`, see #60.)
- In my view it's best to make minimal modifications to the base image for maximal portability and minimal surprise.
- I can't think of any use cases for it.

Does this make sense? Is there some use case I'm missing?

**Comment by wholtz** [comment]
Hi @maresb .
For this sake of this discussion, I'm working off your PR #60.  If the `PATH` modification line is removed, then 3 tests fail. 

Two of these failing tests disable the entrypoint script and I'm okay with that behavior, as people shouldn't be overriding the entrypoint and expect everything to work. Those two tests are primarily in there to ensure the behavior of the image doesn't change without the developers being aware of the implications. 

The third test that fails is this one:
https://github.com/mamba-org/micromamba-docker/blob/92e4c6700d155f9b8bdfb3566866a5f1dfba3e29/test/run-exec-form.Dockerfile#L1-L6

Because that final `RUN` is in the "exec" form, the `SHELL` is not used to evaluate the `RUN` command.  These details of how `RUN` and `SHELL` interact is likely not clear to many users. The modification to `PATH` was done to prevent users from getting hung up on this detail. I'm open to removing this test, but I think the documentation needs to make clear that the shell form of `RUN` is preferred over the exec form when executing a programmed installed to a conda environment.

**Comment by maresb** [comment]
@wholtz, thanks for the detailed explanation!

In this third test, in the context of #60, could you add the line

```Dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1
```

just before the last line? I would expect that to fix this test. At least for me, this behavior is more intuitive: I don't expect anything from the environment to become available until after I have activated it.

**Comment by wholtz** [comment]
No, adding `ARG MAMBA_DOCKERFILE_ACTIVATE=1` does not make the 3rd failing test pass. If you read the Dockerfile docs, this is the expected behavior for the exec form of `RUN`.

**Comment by maresb** [comment]
Ahhhhhhhhhh..... I see.

> These details of how RUN and SHELL interact is likely not clear to many users.

:+1:

Hmm, that does seem to be a significant flaw in my proposal which I had not realized before.

**Comment by wholtz** [comment]
I'm happy with PR #60 and I agree with you overall about modifying the `PATH`.  But I'm going to re-write and expand the docs before I remove the `PATH` modification.

**Comment by maresb** [comment]
> I think the documentation needs to make clear that the shell form of RUN is preferred over the exec form when executing a programmed installed to a conda environment.

This is a really good point. I must confess that I don't understand very well the magic that happens when a Conda binary is executed outside of an activated environment. (I know in Linux there's often some clever shebang stuff.) Do you know to what extent it's equivalent to activating before running?

I suppose the way I'd fix the test case would be

```Dockerfile
RUN ["/opt/conda/bin/python", "-c", "import os; os.system('touch foobar')"] 
```

I'm very glad you like #60, thanks! :smiley:

**Comment by wholtz** [comment]
Done in #63 and #64.

**Comment by maresb** [comment]
This looks great!!! Thanks so much @wholtz!
